import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Generated from the `docs/` folder structure. Order within each level is
 * controlled by each file's `sidebar_position` frontmatter (see docs/*.md).
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
